Problem: (fix #64)Missing docs for nitro-enclave tmkms
crypto-com/chain-docs pull request #65
Opened 2020-12-10 16:04 UTC by allthatjazzleo

Solution: add the setup and configuration procedure.

For Step 5.4, as it is not yet merged to master.
you may need to modify the url or directly use the script without `curl`

2020-12-10 16:04 UTC, allthatjazzleo commented
/staging

2020-12-11 01:46 UTC, tomtau requested changes
I'd probably add some warning that this isn't yet ready for production use: 1) not yet audited, 2) that tmkms prototype fork isn't meant to be maintained in the long term

2020-12-11 04:35 UTC, lezzokafka reviewed
Looks great, some comment first:

2020-12-11 04:35 UTC, lezzokafka commented on docs/getting-started/notes-on-production-deployment.md
> +Take a note of the **consensus / validator public key** `tcrocnclconspub....` for joining validator later.
```suggestion
Take a note of the **consensus / validator public key** with the prefix `tcrocnclconspub....` for joining the network as a validator later.
```

2020-12-11 04:35 UTC, lezzokafka commented on docs/getting-started/notes-on-production-deployment.md
> +Except one last thing one need to further configure `~/.chain-maind/config/config.toml` to enable enclave tmkm to sign.
```suggestion
Except for one last thing one needs to further configure `~/.chain-maind/config/config.toml` to enable enclave tmkm to sign.
```

2020-12-11 05:35 UTC, allthatjazzleo commented
fixed @tomtau @lezzokafka

2020-12-11 05:35 UTC, allthatjazzleo commented
/staging

2020-12-11 07:56 UTC, allthatjazzleo commented
/staging

2020-12-11 09:26 UTC, allthatjazzleo commented
/staging

2020-12-14 06:22 UTC, lezzokafka commented
/staging

2020-12-14 08:59 UTC, allthatjazzleo commented
/staging

2020-12-14 09:23 UTC, allthatjazzleo commented
/staging

2020-12-14 09:52 UTC, lezzokafka approved these changes
Thanks for the great effort!

2020-12-15 02:47 UTC, tomtau commented on docs/getting-started/advanced-tmkms-integration.md
> +Currently, TMKMS provides both **hardware signing** and **softsign**.
```suggestion
Currently, TMKMS provides both **hardware signing** and **softsign**.
 However, it is hard or impossible to plug your own [Hardware Security Modules(HSM)](https://github.com/iqlusioninc/tmkms#hardware-security-modules-recommended) to the major cloud providers when one wants to run it on the cloud for **hardware signing**. On the other hand, it is also insecure to use **softsign** as your generated signing key is actually in plain text on the machine.
```

2020-12-15 02:47 UTC, tomtau commented on docs/getting-started/advanced-tmkms-integration.md
> +However, it is hard or impossible to plug your own [Hardware Security Modules(HSM)](https://github.com/iqlusioninc/tmkms#hardware-security-modules-recommended) to the major cloud providers when one w
```suggestion
Currently, TMKMS provides both **hardware signing** and **softsign**.
 However, it is hard or impossible to plug your own [Hardware Security Modules(HSM)](https://github.com/iqlusioninc/tmkms#hardware-security-modules-recommended) to the major cloud providers when one wants to run it on the cloud for **hardware signing**. On the other hand, it is also insecure to use **softsign** as your generated signing key is actually in plain text on the machine.
```

2020-12-15 02:52 UTC, merged