Croeseid testnet getting-started: update create-validator transaction
crypto-com/chain-docs pull request #70
Opened 2020-12-17 19:39 UTC by angristan

For me and other members of the community on [Discord](https://discord.com/channels/783264383978569728/783264902613565450/789208334800388127),  we needed to add `gas-prices` to fix the `insufficient fee` error. 

Also, since we get 10 test CRO per day on the faucet,  I reduced the amount of the `create-validator` transaction, since a low amount worked for me.

2020-12-19 04:41 UTC, calvinlauco requested changes
@angristan Thanks for the contribution.

The gas prices update looks good to me. However, we don't recommend creating a validator with too less stake because in real life with a small stake you probably won't be able to fit into the validator set. Can you help to revert the amount field?

If you are looking for more TCRO to try setting up the validator, you can ping us in the communication channel and we can send you more.

2020-12-19 04:41 UTC, calvinlauco commented on docs/getting-started/croeseid-testnet.md
> +--amount=1tcro \
```suggestion
--amount=500000tcro \
```

2020-12-19 12:20 UTC, angristan commented on docs/getting-started/croeseid-testnet.md
> +--amount=1tcro \
I see, thanks for the explanation 👍

2020-12-21 02:17 UTC, lezzokafka reviewed
Thanks again for your contribution 👍 
Gas auto with gas adjustment will provide you with a gas estimation so the the `create-validator` transaction  will go on-chain more easily ;)

2020-12-21 02:17 UTC, lezzokafka commented on docs/getting-started/croeseid-testnet.md
> +--gas-prices 0.1basetcro
```suggestion
--gas auto \
--gas-adjustment=1.5
```

2020-12-21 02:52 UTC, merged

2020-12-22 11:41 UTC, angristan commented on docs/getting-started/croeseid-testnet.md
> +--gas-prices 0.1basetcro
That's great! Thanks